### ISSUE TITLE
Why ReShade not works with HLAE?

### ISSUE THREAD

**Issue by bcarusodev** [advancedfx/advancedfx#353] opened 2020-06-22 22:21 UTC
I know it can be recorded with startmovie, but I would like it to work with ReShade since the post-processing effects are much better than in After Effects. They are also native, and if it could be used together with HLAE it would be an extraordinary combination.

**Comment by dtugend** [comment] 2020-06-23 05:25
Because Re-Shade only cares about the on-screen image, while HLAE captures images earlier and even multiple passes/streams during 1 frame.
Closing as duplicate of #63

**Closed as completed by dtugend** 2020-06-23 05:25 UTC
Labels: question
