### ISSUE TITLE
Mesh will not be rendered (grab a programmer!)

### ISSUE THREAD

**Issue by flo306** [advancedfx/advancedfx#187] opened 2019-06-04 16:48 UTC
When i type in the console "mirv_streams record start" the console in CSGO gives me the following error: 

Material afx/greenmatte does not support vertex format used by the mesh (maybe missing fields or mismatched vertex compression?), mesh will not be rendered. Grab a programmer!

I  hope someone can help me fix this bug :)
Things I tried alredy:
- re-instal and download

**Comment by dtugend** [comment] 2019-06-04 17:13
This is a known error message / warning, which happens, because HLAE applies the matte material as replacement to some meshes that don't support the material / shader used for that.

It usually can be safely ignored, since in worst case the mesh in question will not be drawn in the stream in question instead of being masked.

In which way does the bug affect your movie making negatively?

**Comment by flo306** [comment] 2019-06-04 17:16
> 
> 
> This is a known error message / warning, which happens, because HLAE applies the matte material as replacement to some meshes that don't support the material / shader used for that.
> 
> It usually can be safely ignored, since in worst case the mesh in question will not be drawn in the stream in question instead of being masked.
> 
> In which way does the bug affect your movie making negatively?

well sometimes it crashes my csgo

**Comment by dtugend** [comment] 2019-06-04 17:38
Can you please provide the demo, demotime, map location and recording settings, when it happens, so we can try to reproduce the crash?

**Comment by dtugend** [comment] 2019-06-13 20:31
Closing this again, since can't investigate further without your help.

**Closed as completed by dtugend** 2019-06-13 20:31 UTC
Labels: bug
