### ISSUE TITLE
host_framerate makes spectating commands not behave as expected

### ISSUE THREAD

**Issue by Markxy** [advancedfx/advancedfx#674] opened 2021-06-14 14:25 UTC
When setting `host_framerate` to anything other than default (0), the spectating commands work differently.

When `host_framerate` is defaulted, the camera jumps back to player on `-reload` as expected.
With `host_framerate 120` it stays on the grenade.

What I want to do:
- switch to follow grenade when it's being thrown.
- switch off of the grenade at a specific tick after it explodes
- use `host_timescale 0; host_framerate 120` for recording

What I tried:
- using `mirv_time drive 0.5` instead of host_framerate. Produces same results.
- using `mirv_exec {QUOTE}-reload{QUOTE}` instead of `-reload`
- using `spec_next; spec_lock_to_accountid X` with the `-reload`, it is delayed by too much and doesn't execute on given tick.

Not sure if this is HLAE or something with CSGO's internals not working, but maybe there's a good workaround for this.

I've noticed as well that when host_framerate is set to something other than default, when using `spec_next; spec_lock_to_accountid X` elsewhere, it doesn't do it straight away and can take up to a few seconds to do that.

Example .vdm file:
```
"demoactions"
{
	"1"
	{
		factory	"PlayCommands"
		name	"spec"
		starttick	"0"
		commands	"spec_mode 1;spec_next;spec_lock_to_accountid 76561198092541728;cl_spec_follow_grenade_key 2;host_framerate 120"
	}
	"2"
	{
		factory	"SkipAhead"
		name	"SkipAhead8"
		starttick	"1"
		skiptotick	"116110"
	}
	"3"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"+reload"
		starttick	"116350"
	}
	"4"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"-reload"
		startTick	"116558"
	}
	"5"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"demo_togglepause"
		starttick	"117000"
	}
}
```
[Example demo & vdm I'm using - Drive link](https://drive.google.com/file/d/1PlBqYRYQ8VsVEofgcviGwPN-aaKdRN1v/view?usp=sharing)
HLAE version = 2.116.0
HLAE run command (PS):
```
& "E:\HLAE\HLAE.EXE" -csgoLauncher -noGui -autoStart -csgoExe "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe" -gfxEnabled true -gfxWidth 1920 -gfxHeight 1080 -gfxFull true -customLaunchOptions "-steam -game csgo -insecure -applaunch 730 -novid -w 1920 -h 1080 -high -threads 4 +playdemo E:\test\example.dem"
```

**Comment by dtugend** [comment] 2021-06-14 16:21
Hi.

Since there's no HLAE specific commands involved I am guessing it's more of a CS:GO than a HLAE problem for now.

I didn't have time to test it myself yet, so here's a few guesses / comments for now:

Firstly try to follow the smoother demos guide as closely as possible, even if automated:
https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos

Please note that jumping in a demo most certainly messes up the interpolation temporarily, which especially happens when not running real time, even with Smoother Demos guide. It might be a good idea to just start from the start of the round instead and just let it play till the desired action.

What I am guessing is (but not sure about) is that it skips / doesn't hit the "-reload" in the vdm (you can easily test it with an echo at same time maybe).
If that's the reason you can try mirv_cmd as alternative:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_cmd
Still should follow smoothe demos guide though to avoid / minimize a lot of potential problems.

>I've noticed as well that when host_framerate is set to something other than default, when using spec_next;
> spec_lock_to_accountid X elsewhere, it doesn't do it straight away and can take up to a few seconds to do that.

setting host_framearte to s.th. else than default will make the demo not run in realtime, it can run faster or slower, so this behaviour is not unexpected, especially when recording uncompressed it can be much slower.
Especially if there are time interpolation issues due to not following Smoother Demos guide, this can behave quite awkwardly.

**Comment by Markxy** [comment] 2021-06-14 18:16
Thanks Dominik!

You're right, it does look like a CSGO thing.

I was initially following the Smoother Demos guide. For this post I tried to keep it as barebones as possible. I didn't know it would have an effect.

It hits the `-reload`. Previously i had other `mirv_cam` commands that went through on that line. Echo also prints to console.

Now I tried loading all the Smoother Demo variables at tick 0 and setting the skipToTick to the round start, giving it a ~45s lead.
Unfortunately didn't change the result.

It's weird because it executes the `+reload` perfectly, and `-reload` only works without `host_framerate`.
By the way, when manually pressing R on the keyboard, the camera works as expected.

Also sorry for the confusing title, I'm probably mixing multiple things into one here (regarding spectating commands).

**Comment by dtugend** [comment] 2021-06-16 11:38
Hi I tested and found the porblem.
It is not host_framerate, that's a wrong conclusion (probably you reloaded the demo multiple times without disconnecting first causing it to remember the currently spectated player, which has an influence).

The problem is caused by spec_lock_to_accountid xxx not working well together with the gernade follow feature.
To work around it set `spec_lock_to_accountid 0` before +reload and optionally set it back to the old value after -reload:

```
"demoactions"
{
	"1"
	{
		factory	"PlayCommands"
		name	"spec"
		starttick	"0"
		commands	"spec_mode 1;spec_next;spec_lock_to_accountid 76561198092541728;cl_spec_follow_grenade_key 2;host_framerate 120"
	}
	"2"
	{
		factory	"SkipAhead"
		name	"SkipAhead8"
		starttick	"1"
		skiptotick	"116110"
	}
	"3"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"spec_lock_to_accountid 0;+reload"
		starttick	"116350"
	}
	"4"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"-reload;spec_lock_to_accountid 76561198092541728"
		startTick	"116558"
	}
	"5"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"demo_togglepause"
		starttick	"117000"
	}
}
```

This should solve your problem.

**Comment by Markxy** [comment] 2021-06-16 13:09
You're a lifesaver, thanks!

Any way to make this work in POV demos, too?

**Comment by dtugend** [comment] 2021-06-16 13:16
This would need the "opposite" of the mirv_pov command. Considering that POV demos only record what was considered to be visible by the player and some other things it's likely to be bugged in many ways, even if such an "opposite" would exist.

If you know the entity index or handle of the grenade thrown by a player anyway, you might want to look into trying to doing s.th. with [mirv_calcs](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_calcs) instead, but it won't be easy to get something acceptable.

**Comment by dtugend** [comment] 2021-06-16 13:20
Another hint: I don't know if this is for a tool or s.th., but you can also use mirv_pgl to get live data from the game (including all game events, which are a lot) and drive the camera from commands issued live.
The only problem with that is that mirv_pgl doesn't synchronize itself, meaning there will always be some inaccuracies (unlike afx_interop, but that one only supports game events in new version which is not finished / stable yet).

**Comment by Markxy** [comment] 2021-06-16 15:13
Interesting. Well I guess I'm out of luck regarding POV demos, that's not a huge problem though.

Again thanks for all of your help!

**Comment by dtugend** [comment] 2021-06-16 15:46
I guess that means this issue is solved (?), thus closing for now.
If not you can open a new thread e.g. in Discussions tab in Q & A section.

**Closed as completed by dtugend** 2021-06-16 15:46 UTC
Labels: question
