### ISSUE TITLE
HLAE Custom Loader locks up when clicking "Browse"

### ISSUE THREAD

**Issue by Saturn-Enceladus** [advancedfx/advancedfx#103] opened 2018-09-25 01:31 UTC
Clicking "Browse" to choose the ProgramPath or DLL file freezes HLAE. It's been sitting frozen for about 10 minutes now and I don't think it's coming back.
![image](https://user-images.githubusercontent.com/34007473/45987754-dfc91900-c038-11e8-8b54-55926ccf27e0.png)

**Comment by dtugend** [comment] 2018-09-25 05:46
Would be helpful to know your operating system.

The most likely causes are these:
1) You have malware on your system (most likely).
2) Your system (DLL) files are damaged (likely, can also be caused by 1).
3) Your Anti-Virus interferes with HLAE (possible).

Try the following fixes:

For 1)
- Run https://www.malwarebytes.com/adwcleaner/ (will need a reboot)
- Install proper anti-virus, on Windows 10 Windows Defender tends to make a good job, but you need to make sure it's fully updated and enabled

For 2)
- https://support.microsoft.com/en-us/help/4026529/windows-10-using-system-file-checker

**Comment by dtugend** [comment] 2018-10-04 18:30
Hi. Without further feedback it is not possible to try to solve this. Feel free to reply when you have time, closing until then.

**Closed as completed by dtugend** 2018-10-04 18:30 UTC
Labels: question
