### ISSUE TITLE
Hlae not working

### ISSUE THREAD

**Issue by HeadHunterPROFESSOR** [advancedfx/advancedfx#628] opened 2021-04-20 19:10 UTC
when I open csgo from hlae it says that
```
AfxError #12: 
Title: AfxHook errorDescription: Could not access / enter directory of DLL to inject```


![2021-04-20 (2)](https://user-images.githubusercontent.com/82905834/115450923-8e538b80-a22d-11eb-8466-53faf7b7eb35.png)

**Comment by dtugend** [comment] 2021-04-20 20:46
Closing as duplicate of #630.

**Closed as completed by dtugend** 2021-04-20 20:46 UTC
Labels: question
