### ISSUE TITLE
weird video resolution recording with ffmpeg

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#252] opened 2019-12-30 09:21 UTC
Some including me have noticed that when set to 1920*1080, recorded video clips are 1920*1072.
It's kind of weird and does cause little issues like a little left&right or upper&lower part of video is cut, thus causing streching effects (kinda like 16:10 to 16:9).

![image](https://user-images.githubusercontent.com/47248616/71575816-4d5fd100-2b29-11ea-876d-629b2d98c29b.png)

![image](https://user-images.githubusercontent.com/47248616/71575830-594b9300-2b29-11ea-8af0-ae11da46509f.png)

![image](https://user-images.githubusercontent.com/47248616/71575341-8bf48c00-2b27-11ea-9747-8994e4d3d912.png)

**Comment by dtugend** [comment] 2019-12-30 09:29
Please provide the exact settings you used.

**Comment by Purple-CSGO** [comment] 2019-12-30 10:03
> Please provide the exact settings you used.

mirv_streams settings add ffmpeg p2 "-c:v libx264 -preset superfast -crf 16 -pix_fmt yuv422p {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}";
mirv_streams settings edit afxDefault settings p2;
host_framerate 300;

Game resolution is 1920x1080. This issue happens whether its fullscreen or windowed

**Comment by dtugend** [comment] 2019-12-30 10:06
I found a similar problem, but it would only happen in windowed.
Are you really sure it happens in full screen as well?
I will try the setting you provided, but I don't expect problems with those themselves.

## Symptom
Image / video streams have unexpected resolution, or FFMPEG streams don't even record with resolution not dividable by 2 error (e.g. 1920x1071/ instead of 1920x1080)

## Cause of problem
The window does not fully fit into the desktop: e.g. People are using windowed mode on 1920x1080 Desktop, then the title bar and window border will cause it to have less pixels, e.g. 1920x1072.

(This e.g. happens when the resolution is switched after launching the game using `mat_setvideomode 1920 1080 1`.)

## Solution
Use full screen instead of windowed, or don't change resolution after launching the game (assuming the inner area fits into the desktop resolution).

**Comment by dtugend** [comment] 2019-12-30 10:11
I tried your settings in full-screen (so it fits) and they are fine:
- Video res is 1920x1080
- Video buffer res is 1920x1090

Edit: I used these for testing (latest FFMPEG from today):
```
host_framerate 120
mirv_streams settings add ffmpeg p2 "-c:v libx264 -preset superfast -crf 16 -pix_fmt yuv422p {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}";
mirv_streams settings add multi multi
mirv_streams settings edit multi add afxClassic
mirv_streams settings edit multi add p2
mirv_streams add normal norm
mirv_streams edit norm settings multi
mirv_streams record start
```

**If possible please test with VLC Media Player from VideoLan.org to make sure it's not a problem with the player.**

**Comment by Purple-CSGO** [comment] 2019-12-30 10:57
I tested with fullscreen again and it happens.
Right Click -> Properties = 1072.
Use Potplayer and TAB = 1080.
Use another tool to show info = 1080.
Put video into Premiere but it doesn't fully fit. Streched a little bit or 4px black in upper&lower part of screen(When I choose the clip ->right click -> resize to frame size).

I gonna test with the latest ffmpeg later.

**Comment by dtugend** [comment] 2019-12-30 11:25
The reason is that ffmpeg stores no SAR (sample aspect ratio) in the streams by default.

This results in video players / video making programs choosing their default sample aspect ratio, which often enough is not 1:1 but e.g. 10:11.

This can be fixed by embedding the SAR info of 1:1 into the stream, I will update the default settings for next release accordingly in order to avoid these problems:
https://video.stackexchange.com/a/9967

**Comment by Purple-CSGO** [comment] 2019-12-30 11:25
latest version ffmpeg is the same.

I think I know what happened.
My monitor is 2K 2560x1440 and when I record with that res its ok but if I use 1920x1080 res ingame this issue comes, whether I use launch options -w -h or switch to that res and enter the game it's all the same.

**Comment by Purple-CSGO** [comment] 2019-12-30 11:30
> The reason is that ffmpeg stores no SAR (sample aspect ratio) in the streams by default.
> 
> This results in video players / video making programs choosing their default sample aspect ratio, which often enough is not 1:1 but e.g. 10:11.
> 
> This can be fixed by embedding the SAR info of 1:1 into the stream, I will update the default settings for next release accordingly in order to avoid these problems:
> https://video.stackexchange.com/a/9967

So now Can I add SAR 1:1 command into record setting to avoid the problem now?
```
-vf scale=1920x1080,setsar=1:1
```
Is that correct? Sry I only know some basic ffmpeg commands.

**Comment by dtugend** [comment] 2019-12-30 11:33
This won't work, I need to do it inside HLAE, because it already uses `-vf vflip`.

**Comment by Purple-CSGO** [comment] 2019-12-30 11:35
> This won't work, I need to do it inside HLAE, because it already uses `-vf vflip`.

Alright. Sry to bother you so much

**Comment by dtugend** [comment] 2019-12-30 11:39
You can try `-vf vflip,setsar=1:1` until new version is released before the output path, it will override the HLAE option it seems:
```
mirv_streams settings add ffmpeg p2 "-c:v libx264 -preset superfast -crf 16 -pix_fmt yuv422p -vf vflip,setsar=1:1 {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}";
```

Be aware that Windows will still report wrong size in right click properties, but proper video editors should be fine.

**Comment by dtugend** [comment] 2019-12-30 11:48
While it works for 1:1 the syntax I found on stackoverflow is wrong, correct syntax is: `-vf vflip,setsar=sar=1/1`

```
"-c:v libx264 -preset superfast -crf 16 -pix_fmt yuv422p -vf vflip,setsar=sar=1/1 {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}"
```

**Comment by Purple-CSGO** [comment] 2019-12-30 11:55
It does work fine in Premiere. Windows still think it's 1072 LOL
ofc its microsoft

**Closed as completed** 2019-12-30 18:57 UTC
Labels: bug

**Comment by zealotrahl** [comment] 2021-12-15 13:07
Hello guys, did you manage to find the cause of this problem? Facing that video encoded with libx264 specified as 1920x1080 has resolution of 1920x1072

**Comment by dtugend** [comment] 2021-12-15 14:22
As far as we know the problem has been fixed with the commit above in 2019 for all newer HLAE versions.

Your video editor needs to support SAR (Sample Aspect Ratio, also known as PAR (Pixel Aspect Ratio)), otherwise if it simply uses the default SAR for MP4 it will be wrong. For example Adobe Premiere and VLC should work fine, while **Windows 10 1702 Media Player will be wrong** though.

We have had no complaints since then, neither from Sony Vegas nor from Adobe Premiere editors.
