### ISSUE TITLE
When i use Hlae launch csgo,It Crashes To Desktop.No prompt.

### ISSUE THREAD

**Issue by TnE-CsTrk** [advancedfx/advancedfx#354] opened 2020-06-27 16:09 UTC
(Please search exiting **open and closed** issues first to verify this is a new bug report.)

**Comment by TnE-CsTrk** [comment] 2020-06-27 16:10
This problem only appears in the latest version.

**Comment by dtugend** [comment] 2020-06-27 18:57
1) If appending `+mat_queue_mode -1` to the launch options solves the issue, it's a CS:GO (config) related bug and not an HLAE bug, in that case we recommend to use File -> Launch CS:GO and enable the mmcfg folder option and set an new empty folder there. **You should also try this either way in order to make sure you have no config related problems.**
2) What do you get as output when you enter `version` into CS:GO?
3) Do Steam Library -> Right Click CS:GO -> Local Files tab -> Verify Game Cache, let it verify / redownload
4) Also copy & paste the _full_ path from Steam Library -> Right Click CS:GO -> Local Files tab -> Browse Local Files button and append `\csgo.exe` and use that one in HLAE (you current one might be different, since some people end up with multiple CS:GO installs after a while).

**Comment by TnE-CsTrk** [comment] 2020-06-27 19:30
1. the problem still exists
2.version&nbsp;
Protocol&nbsp;version&nbsp;13759&nbsp;[1141/1141]
Exe&nbsp;version&nbsp;1.37.5.9&nbsp;(csgo)
Exe&nbsp;build:&nbsp;12:10:00&nbsp;Jun&nbsp;17&nbsp;2020&nbsp;(7886)&nbsp;(730)
Windows&nbsp;version&nbsp;6.2
3.the problem still exists
4.this exe&nbsp;Can be lunched separately


This problem only appears in the new version.
Maybe need a log to interpret.



9/500











------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik Tugend"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 凌晨2:57
收件人: "advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;; 
抄送: "nova?☆?Ф"<2394066271@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





  
If appending +mat_queue_mode -1 to the launch options solves the issue, it's a CS:GO (config) related bug and not an HLAE bug, in that case we recommend to use File -&gt; Launch CS:GO and enable the mmcfg folder option and set an new empty folder there.
 
What do you get as output when you enter version into CS:GO?
 
Do Steam Library -&gt; Right Click CS:GO -&gt; Local Files tab -&gt; Verify Game Cache, let it verify / redownload
 
Also copy &amp; paste the full path from Steam Library -&gt; Right Click CS:GO -&gt; Local Files tab -&gt; Browse Local Files button and append \csgo.exe and use that one in HLAE (you current one might be different, since some people end up with multiple CS:GO installs after a while).

**Comment by dtugend** [comment] 2020-06-27 20:06
Have you updated your HLAE to latest version too?

**Comment by TnE-CsTrk** [comment] 2020-06-27 20:11
HLAE 2.100.2&nbsp;(2020-06-16T08:03Z)&nbsp;(old versions) (logo)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik Tugend"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 凌晨4:07
收件人: "advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;; 
抄送: "nova?☆?Ф"<2394066271@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





 
Have you updated your HLAE to latest version too?

**Comment by dtugend** [comment] 2020-06-27 20:26
- Can you tell me the size of AfxHookSource.dll in Bytes (the smaller one of the two, not the disk size, only file size), please?
- Are you using File -> Launch CS:GO with custom movie making config folder set and enabled as recommended above?

**Comment by TnE-CsTrk** [comment] 2020-06-27 20:29
883 KB (904,704 字节)
My friend sent me his file but it still doesn't work.
My computer cannot run this version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik Tugend"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 凌晨4:26
收件人: "advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;; 
抄送: "nova?☆?Ф"<2394066271@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





  
Can you tell me the size of AfxHookSource.dll in Bytes (the smaller one of the two, not the disk size, only file size), please?
 
Are you using File -&gt; Launch CS:GO with custom movie making config folder set and enabled as recommended above?

**Comment by dtugend** [comment] 2020-06-27 20:46
- Maybe you can check the Windows Application Event log for errors.
- The crash can also be caused by screen overlays like NIVIDA Shadowplay or others, deactivating the overlay or updating the driver can help.

If you want, send a .mdmp file from the time when it crashed from the csgo.exe folder, or if there's none, check the Steam dumps folder for .dmp: Send it to dominik@matrixstorm.com and include the issue number (354) in the subject please.

**Comment by dtugend** [comment] 2020-06-27 20:47
Addionally to my last message, check if you have an addon / addons folder in your csgo sub-folder (C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo), if yes, please rename or delete it!

**Comment by TnE-CsTrk** [comment] 2020-06-27 20:54
Yes,I have it.
But after I moved it out, the problem was still&nbsp;exists.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik Tugend"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 凌晨4:47
收件人: "advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;; 
抄送: "nova?☆?Ф"<2394066271@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





 
Addionally to my last message, check if you have an addon / addons folder in your csgo sub-folder (C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo), if yes, please rename or delete it!

**Comment by dtugend** [comment] 2020-06-27 21:12
What about the previews message:

> - Maybe you can check the Windows Application Event log for errors.
> - The crash can also be caused by screen overlays like NIVIDA Shadowplay or others, deactivating the overlay or updating the driver can help.
> 
> If you want, send a .mdmp file from the time when it crashed from the csgo.exe folder, or if there's none, check the Steam > dumps folder for .dmp: Send it to dominik@matrixstorm.com and include the issue number (354) in the subject please.

**Comment by TnE-CsTrk** [comment] 2020-06-27 21:42
no .mdmp file from&nbsp;the csgo.exe folder
so many in&nbsp;the Steam &gt; dumps folder when i lunched it create&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dominik Tugend"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 凌晨5:12
收件人:&nbsp;"advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;;
抄送:&nbsp;"nova?☆?Ф"<2394066271@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





 
What about the previews message:
   
Maybe you can check the Windows Application Event log for errors.
 
The crash can also be caused by screen overlays like NIVIDA Shadowplay or others, deactivating the overlay or updating the driver can help.
  
If you want, send a .mdmp file from the time when it crashed from the csgo.exe folder, or if there's none, check the Steam &gt; dumps folder for .dmp: Send it to dominik@matrixstorm.com and include the issue number (354) in the subject please.

**Comment by dtugend** [comment] 2020-06-27 21:52
I only need the latest one from the most recent crash (please pack / compress it e.g. with 7z).

**Comment by TnE-CsTrk** [comment] 2020-06-27 22:16
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dominik Tugend"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 凌晨5:52
收件人:&nbsp;"advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;;
抄送:&nbsp;"nova?☆?Ф"<2394066271@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





 
I only need the latest one from the most recent crash (please pack / compress it e.g. with 7z).

**Comment by dtugend** [comment] 2020-06-28 03:38
You can not send files from email to GitHub issues, also you should not send it publicaly, please send it directly to the email I gave instead.

**Comment by dtugend** [comment] 2020-06-28 04:57
It's crashing inside metamod 2, when loading metamod 2.
i:\program files (x86)\Steam2\steamapps\common\counter-strike global offensive\csgo\addons\metamod\bin\metamod.2.csgo.dll

As said earlier you need to remove / rename the addons folder or update it.

**Comment by TnE-CsTrk** [comment] 2020-06-28 07:34
The issue&nbsp;have been&nbsp;solved.
ps.
I remember clearly that I moved this folder to a celebrity and moved it out.and crash
Maybe he came back after verifying the integrity ....？
Thank you for your selfless help！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik Tugend"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 中午12:57
收件人: "advancedfx/advancedfx"<advancedfx@noreply.github.com&gt;; 
抄送: "nova?☆?Ф"<2394066271@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [advancedfx/advancedfx] When i use Hlae launch csgo,It Crashes To Desktop.No prompt. (#354)





 
It's crashing inside metamod 2, when loading metamod 2.
 i:\program files (x86)\Steam2\steamapps\common\counter-strike global offensive\csgo\addons\metamod\bin\metamod.2.csgo.dll
 
As said earlier you need to remove / rename the addons folder or update it.

**Comment by dtugend** [comment] 2020-06-28 07:44
Closing since it seems solved.

**Closed as completed by dtugend** 2020-06-28 07:44 UTC
Labels: question
