### ISSUE TITLE
afxhook issue

### ISSUE THREAD

**Issue by aprilnoble** [advancedfx/advancedfx#51] opened 2018-06-07 22:00 UTC
I'm always getting this problem while trying to open the game (using the custom loader).
The message it returns is "afxhook error: 3221225177"
Thanks!

**Comment by dtugend** [comment] 2018-06-08 05:57
Since this is not a valid error code, this means the AfxHook.dat code crashed upon injecting.

This can be caused by "behavior blocking" by some Anti Virus programs.

Please try to add an exception for the HLAE.exe process / HLAE folder and check if that makes the issue go away.

**Comment by dtugend** [comment] 2018-06-20 09:37
Closing due to lacking feedback.

**Closed as completed by dtugend** 2018-06-20 09:37 UTC
