### ISSUE TITLE
I don´t get it. How can I fix this problem?

### ISSUE THREAD

**Issue by HeadshotFee** [advancedfx/advancedfx#87] opened 2018-08-01 18:26 UTC
```
AfxError #2000: 
Title: Failed to start injector.
Description: Failed to start injector: C:\Users\Kevin\Desktop\HLAE\\injector.exe
Solution: Check that your Anti Virus did not remove it due to a false positive. If so restore it and add an exception for injector / the HLAE folder.
Inner exception: System.ComponentModel.Win32Exception (0x80004005): Zugriff verweigert
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start()
   bei AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```

**Comment by dtugend** [comment] 2018-08-01 18:54
1) Please make sure to update your Windows Defender definitions (i.e. by installing Windows Updates) or whatever Anti Virus you use.
2) Re-download HLAE.
3) Make sure you extract all files and folders from the official download into an empty folder you like.

**Comment by dtugend** [comment] 2018-08-02 12:51
If it's Windows Defender you might need a reboot.

**Comment by HeadshotFee** [comment] 2018-08-02 23:18
How do you mean that I need a reboot?

Btw I just disabled my Anti Virus (G Data Internet Security) to test if it runs the injector.exe - but nope - there´s still the message I posted above.

**Comment by HeadshotFee** [comment] 2018-08-02 23:25
Oh, if it´s true that you´re from germany we can write in german ^^

**Comment by dtugend** [comment] 2018-08-11 19:57
Closing, because there was no further feedback in the past 9 days.
If the problem is not solved yet, please comment with more information.

**Closed as completed by dtugend** 2018-08-11 19:57 UTC
Labels: question
