### ISSUE TITLE
HLAE scoreboad issue (cs go)

### ISSUE THREAD

**Issue by nkttttt** [advancedfx/advancedfx#102] opened 2018-09-20 07:45 UTC
Hey, while playing demo using hlae in csgo the scoreboard is struck on the screen until the next round starts and i tried everything to remove it but nothing works.

**Comment by nkttttt** [comment] 2018-09-20 07:46
it happens only for the first round after half time

**Comment by dtugend** [comment] 2018-09-20 07:54
I doubt the problem is directly related to HLAE, but let's try to figure it out:

1) Please provide a demo with the problem.
2) If the problem doesn't happen without HLAE, then check that it's not related to your movie making config: use the mmcfg folder feature in File -> Launch CS:GO and set an empty folder.

**Comment by nkttttt** [comment] 2018-09-20 07:58
Hi, Thanks for the fast reply. I will do as suggested and update you for
the same.

Thanks

**Comment by dtugend** [comment] 2018-09-20 08:02
If the problem persists (whether without HLAE or not), try these:

1) Try to enter `-showscores` in console, sometimes that works.
2) You can always hide the scoreboard the hard way: https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

**Comment by nkttttt** [comment] 2018-09-20 08:09
Hi Dominik,

It's a demo bug, happening without hlae also.
I will try the other method you shared.


Thanks for the help :)

**Comment by dtugend** [comment] 2018-09-23 14:31
Hi, I am closing this issue for now, if you have further question(s), feel free to post here.

**Closed as completed by dtugend** 2018-09-23 14:31 UTC
Labels: question
