### ISSUE TITLE
Error Vertex File

### ISSUE THREAD

**Issue by berwil-1** [advancedfx/advancedfx#222] opened 2019-09-08 20:10 UTC
In demos whenever I go near middle (HLAE version 2_80_1)  the following error gets spammed in the CSGO console:

Error Vertex File for 'fmpone/de_cache/workingnewvents.mdl' checksum 2063776429 should be -120802258

**Comment by dtugend** [comment] 2019-09-09 04:20
I can not reproduce the issue.

1) Right click CS:GO in Steam Library -> Properties -> Local File tab -> Verify Game Cache button, let it verify and download if required.

2) Right click CS:GO in Steam Library -> Properties -> Local File tab ->  Brows Local File button, click in the address bar in the Windows Explorer window that opens, to see the full path, if you append "\csgo.exe" it should be the same path you set in HLAE, otherwise please set the same in HLAE (some people have multiple CS:GO installs), the most common path is `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`.

3) Check if it happens without HLAE too or not, if it happens without HLAE, there's not much we can do probably.

4) If it only happens with HLAE:
- We need the exact HLAE features / settings / movie making config you are using.
- We also need the demo.

**Comment by dtugend** [comment] 2019-09-17 18:00
Closing due to lacking feedback.

**Closed as completed by dtugend** 2019-09-17 18:00 UTC
Labels: question
